In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('SMS_test.csv', encoding='latin1')

In [3]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 125):
  spam = re.sub('[^a-zA-Z]', ' ', dataset['Message_body'][i])
  spam = spam.lower()
  spam = spam.split()
  ps = PorterStemmer()
  spam = [ps.stem(word) for word in spam if not word in set(stopwords.words('english'))]
  spam = ' '.join(spam)
  corpus.append(spam)

[nltk_data] Downloading package stopwords to C:\Users\Ashutosh
[nltk_data]     pandey\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [4]:
print(corpus)

['upgrdcentr orang custom may claim free camera phone upgrad loyalti call offer end th juli c appli opt avail', 'loan purpos homeown tenant welcom previous refus still help call free text back help', 'congrat nokia video camera phone call call cost ppm ave call min vari mobil close post bcm ldn wc n xx', 'urgent mobil number award prize guarante call land line claim valid hr', 'someon contact date servic enter phone fanci find call landlin pobox n tf p', 'send logo ur lover name join heart txt love name name mobno eg love adam eve yahoo pobox w wq txtno ad p', 'free entri weekli competit text word win c www txttowin co uk', 'date servic cal l box sk ch', 'free rington text first poli text get true tone help st free tone x pw e nd txt stop', 'mth half price orang line rental latest camera phone free phone mth call mobilesdirect free updat stoptxt', 'doubl min txt month free bluetooth orang avail soni nokia motorola phone call mobileupd call optout n dx', 'thank rington order refer charg

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 753)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, -1].values

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

In [7]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [8]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Spam' 'Spam']
 ['Spam' 'Spam']
 ['Spam' 'Spam']
 ['Spam' 'Non-Spam']
 ['Spam' 'Spam']
 ['Non-Spam' 'Non-Spam']
 ['Spam' 'Spam']
 ['Spam' 'Non-Spam']
 ['Spam' 'Non-Spam']
 ['Spam' 'Spam']
 ['Spam' 'Spam']
 ['Non-Spam' 'Non-Spam']
 ['Spam' 'Spam']
 ['Non-Spam' 'Non-Spam']
 ['Spam' 'Spam']
 ['Non-Spam' 'Non-Spam']
 ['Spam' 'Spam']
 ['Non-Spam' 'Non-Spam']
 ['Spam' 'Spam']
 ['Spam' 'Non-Spam']
 ['Spam' 'Spam']
 ['Spam' 'Non-Spam']
 ['Spam' 'Spam']
 ['Spam' 'Spam']
 ['Spam' 'Spam']]


In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 5  5]
 [ 0 15]]


0.8

In [10]:
print(X_test)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
new_mail = 'hi i am ashu'
new_mail = re.sub('[^a-zA-Z]', ' ', new_mail)
new_mail = new_mail.lower()
new_mail = new_mail.split()
ps = PorterStemmer()
new_mail = [ps.stem(word) for word in new_mail if not word in set(stopwords.words('english'))]
new_mail = ' '.join(new_mail)
new_corpus = [new_mail]
new_X_test = cv.transform(new_corpus).toarray()
new_y_pred = classifier.predict(new_X_test)
print(new_y_pred)

['Non-Spam']
